# Generated by Django 5.1.1 on 2024-10-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('staffid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('staffpass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('landID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('landName', models.CharField(max_length=100)),
                ('landNo', models.CharField(max_length=20)),
                ('landPass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('studName', models.CharField(max_length=100)),
                ('studPass', models.CharField(max_length=60)),
                ('studGender', models.CharField(max_length=10)),
                ('studNo', models.CharField(max_length=20)),
                ('guardNo', models.CharField(max_length=20)),
                ('studAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('propID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('propType', models.CharField(max_length=30)),
                ('propSize', models.CharField(max_length=100)),
                ('propPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propLoc', models.CharField(max_length=30)),
                ('landID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houserental.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100)),
                ('m_date', models.DateField()),
                ('m_time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('propID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houserental.properties')),
                ('studID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houserental.student')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('propID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houserental.properties')),
                ('studID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houserental.student')),
            ],
        ),
    ]
