# Generated by Django 5.1.1 on 2024-10-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houserental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='m_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='m_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
